# -*- coding: utf-8 -*-
"""RAP_testing3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1epR4NoUh9UGdhI1w3Cz-WnN63LnpsZCd
"""

import pandas as pd
import os
import numpy as np
clear = lambda:os.system('cls')
num = int (input("Enter the number of people :"))
name =[]
amount_paid = []
for i in range(num):
  n = input("Enter the name of the person : ")
  a = int(input("Enter the amount paid by that person : "))
  name.append(n)
  amount_paid.append(a)
dat = {'Name':name,'amount paid':amount_paid}
df = pd.DataFrame(dat)
print(df)
print("total amount paid is ",df.sum())

